### ISSUE TITLE
How this will help with aws-amplify SSR issue

### ISSUE THREAD

**Issue by Arunaliyanaarachchi** [ntegral/ngx-amplify#1]
hi,
i have application develop for 90% and found out that angular normal setup not work for google search.so tried to integrate angular universal for SSR.so encountered with amplify issue.amplify not supporting for  SSR. since authentication is one of the main part in my application it very hard to reverse this back.so can you please describe me how this ngx-amplify help to solve this issue ..?

**Comment by ntegral** [comment]
what features are you using in addition to authentication.  I created the library because I ran into the same issue with my application.  Note: ngx-amplify only focuses on authentication and s3 storage currently.  However, it will work using angular SSR.  If you could provide more details about the issues that you are experiencing, I could possible provide greater details.  

The other feature that ngx-amplify supports that amplify did not support at the time that I created the package was custom aws attributes..

Hope that this helps
